/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.hamd.quanlymotcua.model.impl;

import com.hamd.quanlymotcua.model.HoSoMotCua;
import com.hamd.quanlymotcua.model.HoSoMotCuaModel;
import com.hamd.quanlymotcua.model.HoSoMotCuaSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the HoSoMotCua service. Represents a row in the &quot;mc_hosomotcua&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.hamd.quanlymotcua.model.HoSoMotCuaModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link HoSoMotCuaImpl}.
 * </p>
 *
 * @author hamd
 * @see HoSoMotCuaImpl
 * @see com.hamd.quanlymotcua.model.HoSoMotCua
 * @see com.hamd.quanlymotcua.model.HoSoMotCuaModel
 * @generated
 */
@JSON(strict = true)
public class HoSoMotCuaModelImpl extends BaseModelImpl<HoSoMotCua>
	implements HoSoMotCuaModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ho so mot cua model instance should use the {@link com.hamd.quanlymotcua.model.HoSoMotCua} interface instead.
	 */
	public static final String TABLE_NAME = "mc_hosomotcua";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.INTEGER },
			{ "ten_don_vi", Types.VARCHAR },
			{ "dien_thoai", Types.VARCHAR },
			{ "ten_nguoi_nop", Types.VARCHAR },
			{ "cmnd", Types.VARCHAR },
			{ "dien_thoai_nguoi_nop", Types.VARCHAR },
			{ "dia_chi", Types.VARCHAR },
			{ "loai_ho_so", Types.INTEGER },
			{ "id_thu_tuc", Types.INTEGER },
			{ "ngay_tiep_nhan", Types.TIMESTAMP },
			{ "ngay_tra_ket_qua", Types.TIMESTAMP },
			{ "hinh_thuc_nop", Types.INTEGER },
			{ "ma_ho_so", Types.VARCHAR },
			{ "so_bo_ho_so", Types.INTEGER },
			{ "trang_thai", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table mc_hosomotcua (id_ INTEGER not null primary key,ten_don_vi VARCHAR(255) null,dien_thoai VARCHAR(75) null,ten_nguoi_nop VARCHAR(255) null,cmnd VARCHAR(75) null,dien_thoai_nguoi_nop VARCHAR(75) null,dia_chi VARCHAR(255) null,loai_ho_so INTEGER,id_thu_tuc INTEGER,ngay_tiep_nhan DATE null,ngay_tra_ket_qua DATE null,hinh_thuc_nop INTEGER,ma_ho_so VARCHAR(75) null,so_bo_ho_so INTEGER,trang_thai INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table mc_hosomotcua";
	public static final String ORDER_BY_JPQL = " ORDER BY hoSoMotCua.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY mc_hosomotcua.id_ ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.hamd.quanlymotcua.model.HoSoMotCua"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.hamd.quanlymotcua.model.HoSoMotCua"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static HoSoMotCua toModel(HoSoMotCuaSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		HoSoMotCua model = new HoSoMotCuaImpl();

		model.setId(soapModel.getId());
		model.setTenDonVi(soapModel.getTenDonVi());
		model.setDienThoai(soapModel.getDienThoai());
		model.setTenNguoiNop(soapModel.getTenNguoiNop());
		model.setCMND(soapModel.getCMND());
		model.setDienThoaiNguoiNop(soapModel.getDienThoaiNguoiNop());
		model.setDiaChi(soapModel.getDiaChi());
		model.setLoaiHoSo(soapModel.getLoaiHoSo());
		model.setIDThuTuc(soapModel.getIDThuTuc());
		model.setNgayTiepNhan(soapModel.getNgayTiepNhan());
		model.setNgayTraKetQua(soapModel.getNgayTraKetQua());
		model.setHinhThucNop(soapModel.getHinhThucNop());
		model.setMaHoSo(soapModel.getMaHoSo());
		model.setSoBoHoSo(soapModel.getSoBoHoSo());
		model.setTrangThai(soapModel.getTrangThai());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<HoSoMotCua> toModels(HoSoMotCuaSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<HoSoMotCua> models = new ArrayList<HoSoMotCua>(soapModels.length);

		for (HoSoMotCuaSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.hamd.quanlymotcua.model.HoSoMotCua"));

	public HoSoMotCuaModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return HoSoMotCua.class;
	}

	@Override
	public String getModelClassName() {
		return HoSoMotCua.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("TenDonVi", getTenDonVi());
		attributes.put("DienThoai", getDienThoai());
		attributes.put("TenNguoiNop", getTenNguoiNop());
		attributes.put("CMND", getCMND());
		attributes.put("DienThoaiNguoiNop", getDienThoaiNguoiNop());
		attributes.put("DiaChi", getDiaChi());
		attributes.put("LoaiHoSo", getLoaiHoSo());
		attributes.put("IDThuTuc", getIDThuTuc());
		attributes.put("NgayTiepNhan", getNgayTiepNhan());
		attributes.put("NgayTraKetQua", getNgayTraKetQua());
		attributes.put("HinhThucNop", getHinhThucNop());
		attributes.put("MaHoSo", getMaHoSo());
		attributes.put("SoBoHoSo", getSoBoHoSo());
		attributes.put("TrangThai", getTrangThai());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer id = (Integer)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String TenDonVi = (String)attributes.get("TenDonVi");

		if (TenDonVi != null) {
			setTenDonVi(TenDonVi);
		}

		String DienThoai = (String)attributes.get("DienThoai");

		if (DienThoai != null) {
			setDienThoai(DienThoai);
		}

		String TenNguoiNop = (String)attributes.get("TenNguoiNop");

		if (TenNguoiNop != null) {
			setTenNguoiNop(TenNguoiNop);
		}

		String CMND = (String)attributes.get("CMND");

		if (CMND != null) {
			setCMND(CMND);
		}

		String DienThoaiNguoiNop = (String)attributes.get("DienThoaiNguoiNop");

		if (DienThoaiNguoiNop != null) {
			setDienThoaiNguoiNop(DienThoaiNguoiNop);
		}

		String DiaChi = (String)attributes.get("DiaChi");

		if (DiaChi != null) {
			setDiaChi(DiaChi);
		}

		Integer LoaiHoSo = (Integer)attributes.get("LoaiHoSo");

		if (LoaiHoSo != null) {
			setLoaiHoSo(LoaiHoSo);
		}

		Integer IDThuTuc = (Integer)attributes.get("IDThuTuc");

		if (IDThuTuc != null) {
			setIDThuTuc(IDThuTuc);
		}

		Date NgayTiepNhan = (Date)attributes.get("NgayTiepNhan");

		if (NgayTiepNhan != null) {
			setNgayTiepNhan(NgayTiepNhan);
		}

		Date NgayTraKetQua = (Date)attributes.get("NgayTraKetQua");

		if (NgayTraKetQua != null) {
			setNgayTraKetQua(NgayTraKetQua);
		}

		Integer HinhThucNop = (Integer)attributes.get("HinhThucNop");

		if (HinhThucNop != null) {
			setHinhThucNop(HinhThucNop);
		}

		String MaHoSo = (String)attributes.get("MaHoSo");

		if (MaHoSo != null) {
			setMaHoSo(MaHoSo);
		}

		Integer SoBoHoSo = (Integer)attributes.get("SoBoHoSo");

		if (SoBoHoSo != null) {
			setSoBoHoSo(SoBoHoSo);
		}

		Integer TrangThai = (Integer)attributes.get("TrangThai");

		if (TrangThai != null) {
			setTrangThai(TrangThai);
		}
	}

	@JSON
	@Override
	public int getId() {
		return _id;
	}

	@Override
	public void setId(int id) {
		_id = id;
	}

	@JSON
	@Override
	public String getTenDonVi() {
		if (_TenDonVi == null) {
			return StringPool.BLANK;
		}
		else {
			return _TenDonVi;
		}
	}

	@Override
	public void setTenDonVi(String TenDonVi) {
		_TenDonVi = TenDonVi;
	}

	@JSON
	@Override
	public String getDienThoai() {
		if (_DienThoai == null) {
			return StringPool.BLANK;
		}
		else {
			return _DienThoai;
		}
	}

	@Override
	public void setDienThoai(String DienThoai) {
		_DienThoai = DienThoai;
	}

	@JSON
	@Override
	public String getTenNguoiNop() {
		if (_TenNguoiNop == null) {
			return StringPool.BLANK;
		}
		else {
			return _TenNguoiNop;
		}
	}

	@Override
	public void setTenNguoiNop(String TenNguoiNop) {
		_TenNguoiNop = TenNguoiNop;
	}

	@JSON
	@Override
	public String getCMND() {
		if (_CMND == null) {
			return StringPool.BLANK;
		}
		else {
			return _CMND;
		}
	}

	@Override
	public void setCMND(String CMND) {
		_CMND = CMND;
	}

	@JSON
	@Override
	public String getDienThoaiNguoiNop() {
		if (_DienThoaiNguoiNop == null) {
			return StringPool.BLANK;
		}
		else {
			return _DienThoaiNguoiNop;
		}
	}

	@Override
	public void setDienThoaiNguoiNop(String DienThoaiNguoiNop) {
		_DienThoaiNguoiNop = DienThoaiNguoiNop;
	}

	@JSON
	@Override
	public String getDiaChi() {
		if (_DiaChi == null) {
			return StringPool.BLANK;
		}
		else {
			return _DiaChi;
		}
	}

	@Override
	public void setDiaChi(String DiaChi) {
		_DiaChi = DiaChi;
	}

	@JSON
	@Override
	public int getLoaiHoSo() {
		return _LoaiHoSo;
	}

	@Override
	public void setLoaiHoSo(int LoaiHoSo) {
		_LoaiHoSo = LoaiHoSo;
	}

	@JSON
	@Override
	public int getIDThuTuc() {
		return _IDThuTuc;
	}

	@Override
	public void setIDThuTuc(int IDThuTuc) {
		_IDThuTuc = IDThuTuc;
	}

	@JSON
	@Override
	public Date getNgayTiepNhan() {
		return _NgayTiepNhan;
	}

	@Override
	public void setNgayTiepNhan(Date NgayTiepNhan) {
		_NgayTiepNhan = NgayTiepNhan;
	}

	@JSON
	@Override
	public Date getNgayTraKetQua() {
		return _NgayTraKetQua;
	}

	@Override
	public void setNgayTraKetQua(Date NgayTraKetQua) {
		_NgayTraKetQua = NgayTraKetQua;
	}

	@JSON
	@Override
	public int getHinhThucNop() {
		return _HinhThucNop;
	}

	@Override
	public void setHinhThucNop(int HinhThucNop) {
		_HinhThucNop = HinhThucNop;
	}

	@JSON
	@Override
	public String getMaHoSo() {
		if (_MaHoSo == null) {
			return StringPool.BLANK;
		}
		else {
			return _MaHoSo;
		}
	}

	@Override
	public void setMaHoSo(String MaHoSo) {
		_MaHoSo = MaHoSo;
	}

	@JSON
	@Override
	public int getSoBoHoSo() {
		return _SoBoHoSo;
	}

	@Override
	public void setSoBoHoSo(int SoBoHoSo) {
		_SoBoHoSo = SoBoHoSo;
	}

	@JSON
	@Override
	public int getTrangThai() {
		return _TrangThai;
	}

	@Override
	public void setTrangThai(int TrangThai) {
		_TrangThai = TrangThai;
	}

	@Override
	public HoSoMotCua toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (HoSoMotCua)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		HoSoMotCuaImpl hoSoMotCuaImpl = new HoSoMotCuaImpl();

		hoSoMotCuaImpl.setId(getId());
		hoSoMotCuaImpl.setTenDonVi(getTenDonVi());
		hoSoMotCuaImpl.setDienThoai(getDienThoai());
		hoSoMotCuaImpl.setTenNguoiNop(getTenNguoiNop());
		hoSoMotCuaImpl.setCMND(getCMND());
		hoSoMotCuaImpl.setDienThoaiNguoiNop(getDienThoaiNguoiNop());
		hoSoMotCuaImpl.setDiaChi(getDiaChi());
		hoSoMotCuaImpl.setLoaiHoSo(getLoaiHoSo());
		hoSoMotCuaImpl.setIDThuTuc(getIDThuTuc());
		hoSoMotCuaImpl.setNgayTiepNhan(getNgayTiepNhan());
		hoSoMotCuaImpl.setNgayTraKetQua(getNgayTraKetQua());
		hoSoMotCuaImpl.setHinhThucNop(getHinhThucNop());
		hoSoMotCuaImpl.setMaHoSo(getMaHoSo());
		hoSoMotCuaImpl.setSoBoHoSo(getSoBoHoSo());
		hoSoMotCuaImpl.setTrangThai(getTrangThai());

		hoSoMotCuaImpl.resetOriginalValues();

		return hoSoMotCuaImpl;
	}

	@Override
	public int compareTo(HoSoMotCua hoSoMotCua) {
		int primaryKey = hoSoMotCua.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof HoSoMotCua)) {
			return false;
		}

		HoSoMotCua hoSoMotCua = (HoSoMotCua)obj;

		int primaryKey = hoSoMotCua.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<HoSoMotCua> toCacheModel() {
		HoSoMotCuaCacheModel hoSoMotCuaCacheModel = new HoSoMotCuaCacheModel();

		hoSoMotCuaCacheModel.id = getId();

		hoSoMotCuaCacheModel.TenDonVi = getTenDonVi();

		String TenDonVi = hoSoMotCuaCacheModel.TenDonVi;

		if ((TenDonVi != null) && (TenDonVi.length() == 0)) {
			hoSoMotCuaCacheModel.TenDonVi = null;
		}

		hoSoMotCuaCacheModel.DienThoai = getDienThoai();

		String DienThoai = hoSoMotCuaCacheModel.DienThoai;

		if ((DienThoai != null) && (DienThoai.length() == 0)) {
			hoSoMotCuaCacheModel.DienThoai = null;
		}

		hoSoMotCuaCacheModel.TenNguoiNop = getTenNguoiNop();

		String TenNguoiNop = hoSoMotCuaCacheModel.TenNguoiNop;

		if ((TenNguoiNop != null) && (TenNguoiNop.length() == 0)) {
			hoSoMotCuaCacheModel.TenNguoiNop = null;
		}

		hoSoMotCuaCacheModel.CMND = getCMND();

		String CMND = hoSoMotCuaCacheModel.CMND;

		if ((CMND != null) && (CMND.length() == 0)) {
			hoSoMotCuaCacheModel.CMND = null;
		}

		hoSoMotCuaCacheModel.DienThoaiNguoiNop = getDienThoaiNguoiNop();

		String DienThoaiNguoiNop = hoSoMotCuaCacheModel.DienThoaiNguoiNop;

		if ((DienThoaiNguoiNop != null) && (DienThoaiNguoiNop.length() == 0)) {
			hoSoMotCuaCacheModel.DienThoaiNguoiNop = null;
		}

		hoSoMotCuaCacheModel.DiaChi = getDiaChi();

		String DiaChi = hoSoMotCuaCacheModel.DiaChi;

		if ((DiaChi != null) && (DiaChi.length() == 0)) {
			hoSoMotCuaCacheModel.DiaChi = null;
		}

		hoSoMotCuaCacheModel.LoaiHoSo = getLoaiHoSo();

		hoSoMotCuaCacheModel.IDThuTuc = getIDThuTuc();

		Date NgayTiepNhan = getNgayTiepNhan();

		if (NgayTiepNhan != null) {
			hoSoMotCuaCacheModel.NgayTiepNhan = NgayTiepNhan.getTime();
		}
		else {
			hoSoMotCuaCacheModel.NgayTiepNhan = Long.MIN_VALUE;
		}

		Date NgayTraKetQua = getNgayTraKetQua();

		if (NgayTraKetQua != null) {
			hoSoMotCuaCacheModel.NgayTraKetQua = NgayTraKetQua.getTime();
		}
		else {
			hoSoMotCuaCacheModel.NgayTraKetQua = Long.MIN_VALUE;
		}

		hoSoMotCuaCacheModel.HinhThucNop = getHinhThucNop();

		hoSoMotCuaCacheModel.MaHoSo = getMaHoSo();

		String MaHoSo = hoSoMotCuaCacheModel.MaHoSo;

		if ((MaHoSo != null) && (MaHoSo.length() == 0)) {
			hoSoMotCuaCacheModel.MaHoSo = null;
		}

		hoSoMotCuaCacheModel.SoBoHoSo = getSoBoHoSo();

		hoSoMotCuaCacheModel.TrangThai = getTrangThai();

		return hoSoMotCuaCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(31);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", TenDonVi=");
		sb.append(getTenDonVi());
		sb.append(", DienThoai=");
		sb.append(getDienThoai());
		sb.append(", TenNguoiNop=");
		sb.append(getTenNguoiNop());
		sb.append(", CMND=");
		sb.append(getCMND());
		sb.append(", DienThoaiNguoiNop=");
		sb.append(getDienThoaiNguoiNop());
		sb.append(", DiaChi=");
		sb.append(getDiaChi());
		sb.append(", LoaiHoSo=");
		sb.append(getLoaiHoSo());
		sb.append(", IDThuTuc=");
		sb.append(getIDThuTuc());
		sb.append(", NgayTiepNhan=");
		sb.append(getNgayTiepNhan());
		sb.append(", NgayTraKetQua=");
		sb.append(getNgayTraKetQua());
		sb.append(", HinhThucNop=");
		sb.append(getHinhThucNop());
		sb.append(", MaHoSo=");
		sb.append(getMaHoSo());
		sb.append(", SoBoHoSo=");
		sb.append(getSoBoHoSo());
		sb.append(", TrangThai=");
		sb.append(getTrangThai());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(49);

		sb.append("<model><model-name>");
		sb.append("com.hamd.quanlymotcua.model.HoSoMotCua");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>TenDonVi</column-name><column-value><![CDATA[");
		sb.append(getTenDonVi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DienThoai</column-name><column-value><![CDATA[");
		sb.append(getDienThoai());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>TenNguoiNop</column-name><column-value><![CDATA[");
		sb.append(getTenNguoiNop());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CMND</column-name><column-value><![CDATA[");
		sb.append(getCMND());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DienThoaiNguoiNop</column-name><column-value><![CDATA[");
		sb.append(getDienThoaiNguoiNop());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DiaChi</column-name><column-value><![CDATA[");
		sb.append(getDiaChi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>LoaiHoSo</column-name><column-value><![CDATA[");
		sb.append(getLoaiHoSo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>IDThuTuc</column-name><column-value><![CDATA[");
		sb.append(getIDThuTuc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>NgayTiepNhan</column-name><column-value><![CDATA[");
		sb.append(getNgayTiepNhan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>NgayTraKetQua</column-name><column-value><![CDATA[");
		sb.append(getNgayTraKetQua());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>HinhThucNop</column-name><column-value><![CDATA[");
		sb.append(getHinhThucNop());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>MaHoSo</column-name><column-value><![CDATA[");
		sb.append(getMaHoSo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>SoBoHoSo</column-name><column-value><![CDATA[");
		sb.append(getSoBoHoSo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>TrangThai</column-name><column-value><![CDATA[");
		sb.append(getTrangThai());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = HoSoMotCua.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			HoSoMotCua.class
		};
	private int _id;
	private String _TenDonVi;
	private String _DienThoai;
	private String _TenNguoiNop;
	private String _CMND;
	private String _DienThoaiNguoiNop;
	private String _DiaChi;
	private int _LoaiHoSo;
	private int _IDThuTuc;
	private Date _NgayTiepNhan;
	private Date _NgayTraKetQua;
	private int _HinhThucNop;
	private String _MaHoSo;
	private int _SoBoHoSo;
	private int _TrangThai;
	private HoSoMotCua _escapedModel;
}